- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx] 
  static_configs:
    - targets:
        - http://prometheus.io     
        - http://IP:3000 
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 13.232.214.2:9115  

- job_name: 'jenkins'
  metrics_path: '/prometheus'
  static_configs:
    - targets:
        - 'ip:8080'


- job_name: node_exporter
  static_configs:
    - targets:
        - 'IP:9100'

